# Generated by Django 2.1.2 on 2018-10-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macropack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermacropack',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
