# Generated by Django 2.1.2 on 2018-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macropack', '0002_auto_20181025_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermacropack',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='usermacropack',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
