# Generated by Django 2.1.2 on 2018-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macropack', '0003_auto_20181025_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissoesClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('macropack_permissoes', 'Permissão Global de Macropack'),),
                'managed': False,
            },
        ),
    ]
