# Generated by Django 2.1.2 on 2018-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macropack', '0005_permissoesmacropack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermacropack',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
    ]
